/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    AccountCard: typeof import('./src/components/AccountCard.vue')['default']
    AddAccountModal: typeof import('./src/components/AddAccountModal.vue')['default']
    AddBudgetModal: typeof import('./src/components/AddBudgetModal.vue')['default']
    AddInvestmentAssetModal: typeof import('./src/components/AddInvestmentAssetModal.vue')['default']
    AddTransactionModal: typeof import('./src/components/AddTransactionModal.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseTooltip: typeof import('./src/components/BaseTooltip.vue')['default']
    BudgetControlPanel: typeof import('./src/components/BudgetControlPanel.vue')['default']
    BudgetSummaryExpenses: typeof import('./src/components/BudgetSummaryExpenses.vue')['default']
    BudgetSummaryIncome: typeof import('./src/components/BudgetSummaryIncome.vue')['default']
    BudgetSummaryNet: typeof import('./src/components/BudgetSummaryNet.vue')['default']
    BudgetSummaryRow: typeof import('./src/components/BudgetSummaryRow.vue')['default']
    BudgetSummaryRowHelper: typeof import('./src/components/BudgetSummaryRowHelper.vue')['default']
    BudgetTable: typeof import('./src/components/BudgetTable.vue')['default']
    BudgetTableGrouped: typeof import('./src/components/BudgetTableGrouped.vue')['default']
    BudgetTableList: typeof import('./src/components/BudgetTableList.vue')['default']
    BudgetTableRow: typeof import('./src/components/BudgetTableRow.vue')['default']
    BudgetTableSummary: typeof import('./src/components/BudgetTableSummary.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    CloseMonthModal: typeof import('./src/components/CloseMonthModal.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CurrencyInput: typeof import('./src/components/CurrencyInput.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditAccountModal: typeof import('./src/components/EditAccountModal.vue')['default']
    ExpenseBreakdownChart: typeof import('./src/components/ExpenseBreakdownChart.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HistoryModal: typeof import('./src/components/HistoryModal.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MonthlyTrendChart: typeof import('./src/components/MonthlyTrendChart.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProjectionChart: typeof import('./src/components/ProjectionChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Toaster: typeof import('./src/components/Toaster.vue')['default']
    TransferModal: typeof import('./src/components/TransferModal.vue')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
